# Generated by Django 3.1.7 on 2021-04-06 13:40

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название филиала')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Словарь филиалов',
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Название операции')),
            ],
            options={
                'verbose_name': 'Операцию',
                'verbose_name_plural': 'Словарь операций',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название источника')),
            ],
            options={
                'verbose_name': 'Источник',
                'verbose_name_plural': 'Словарь источников',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Ед. изм. тех. параметра')),
            ],
            options={
                'verbose_name': 'Единицу измерения',
                'verbose_name_plural': 'Словарь ед. измерения',
            },
        ),
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название скважины')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.branch', verbose_name='Филиал')),
            ],
            options={
                'verbose_name': 'Скважину',
                'verbose_name_plural': 'Словарь скважин',
            },
        ),
        migrations.CreateModel(
            name='TechParamsDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название тех. параметра')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.unit', verbose_name='Ед. изм. тех. параметра')),
            ],
            options={
                'verbose_name': 'Тех. параметр',
                'verbose_name_plural': 'Словарь тех.параметров',
            },
        ),
        migrations.CreateModel(
            name='TechParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=6, max_digits=12, verbose_name='Значение тех. параметра')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.techparamsdict', verbose_name='Название тех. параметра')),
                ('well', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='well', to='api.well', verbose_name='Операция')),
            ],
            options={
                'verbose_name': 'Тех.параметр операции',
                'verbose_name_plural': 'Тех.параметры операции',
            },
        ),
        migrations.CreateModel(
            name='DrillingOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drill_date', models.DateField(verbose_name='Дата')),
                ('time_start', models.TimeField(verbose_name='Начало (время)')),
                ('time_end', models.TimeField(verbose_name='Окончание (время)')),
                ('duration', models.DurationField(verbose_name='Длительность (мин.)')),
                ('chisel_depth_start', models.DecimalField(decimal_places=6, max_digits=12, verbose_name='Глубина долота на начало операции')),
                ('chisel_depth_end', models.DecimalField(decimal_places=6, max_digits=12, verbose_name='Глубина долота на окончание операции')),
                ('candles_amount', models.PositiveIntegerField(verbose_name='Количество свечей')),
                ('slaughter_depth_start', models.DecimalField(decimal_places=6, max_digits=12, verbose_name='Глубина забоя на начало операции')),
                ('slaughter_depth_end', models.DecimalField(decimal_places=6, max_digits=12, verbose_name='Глубина забоя на окончание операции')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.operation', verbose_name='Операция')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.source', verbose_name='Источник')),
                ('tech_params', models.ManyToManyField(to='api.TechParam', verbose_name='Тех. параметры')),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.well', verbose_name='Скважина')),
            ],
            options={
                'verbose_name': 'Операцию бурения скважины',
                'verbose_name_plural': 'Операции бурения скважин',
            },
        ),
    ]
