# Generated by Django 3.1.7 on 2021-04-06 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techparam',
            name='level',
        ),
        migrations.RemoveField(
            model_name='techparam',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='techparam',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='techparam',
            name='tree_id',
        ),
        migrations.RemoveField(
            model_name='techparam',
            name='well',
        ),
        migrations.RemoveField(
            model_name='well',
            name='level',
        ),
        migrations.RemoveField(
            model_name='well',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='well',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='well',
            name='tree_id',
        ),
    ]
