# Generated by Django 3.1.7 on 2021-04-03 19:33

from django.db import migrations


def create_data(apps, schema_editor):
    Customer = apps.get_model('customers', 'Customer')
    Customer(date="skip",
             begin_time="skip",
             end_time="skip",
             bit_begin="skip",
             bit_end="skip",
             candles="skip",
             operation="skip",
             tech_parameters="skip",
             bottomhole_begin="skip",
             bottomhole_end="skip",
             source_name="skip").save()


class Migration(migrations.Migration):
    dependencies = [
        ('customers', '0001_initial'),
    ]
    operations = [
        migrations.RunPython(create_data),
    ]
