# Generated by Django 3.1.7 on 2021-04-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drill_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationclass',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
