# Generated by Django 3.1.7 on 2021-04-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drill_data', '0002_auto_20210402_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='group_name',
        ),
        migrations.AddField(
            model_name='operation',
            name='feature',
            field=models.FloatField(default=0, verbose_name='Нагрузка на крюке'),
            preserve_default=False,
        ),
    ]
