# Generated by Django 3.1.7 on 2021-04-02 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drill_data', '0003_auto_20210402_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='drillfloor',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drillfloor',
            name='director',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='drill_data.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drillfloor',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operation',
            name='base_file',
            field=models.FileField(default='', upload_to='data/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operation',
            name='date_time',
            field=models.DateTimeField(auto_created=True, default='2021-12-12 15:14:14'),
            preserve_default=False,
        ),
    ]
