# Generated by Django 3.1.7 on 2021-04-02 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drill_data', '0004_auto_20210402_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='drill_floor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='drill_data.drillfloor'),
            preserve_default=False,
        ),
    ]
